# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Drug.destroy_all
SideEffect.destroy_all
DrugEffect.destroy_all

drowsiness = SideEffect.create(description: 'Drowsiness')
dry_mouth = SideEffect.create(description: 'Dry Mouth')
dizziness = SideEffect.create(description: 'Dizziness')
blurred_vision = SideEffect.create(description: 'Blurred Vision')
constipation = SideEffect.create(description: 'Constipation')
weight_gain = SideEffect.create(description: 'Weight Gain')
weight_loss = SideEffect.create(description: 'Weight Loss')
trouble_urinating = SideEffect.create(description: 'Trouble Urinating')
headache = SideEffect.create(description: 'Headache')
increased_appetite = SideEffect.create(description: 'Increased Appetite')
decreased_appetite = SideEffect.create(description: 'Decreased Appetite')
changes_in_taste = SideEffect.create(description: 'Changes In Taste')
fast_heart_rate = SideEffect.create(description: 'Fast Heart Rate')
tingly_feeling = SideEffect.create(description: 'Tingly Feeling')
weakness = SideEffect.create(description: 'Weakness')
lack_of_coordination = SideEffect.create(description: 'Lack Of Coordination')
unpleasant_taste = SideEffect.create(description: 'Unpleasant Taste')
nausea = SideEffect.create(description: 'Nausea')
ringing = SideEffect.create(description: 'Ringing in Ears')
breast_swelling = SideEffect.create(description: 'Breast Swelling')
decreased_sex_drive = SideEffect.create(description: 'Decreased Sex Drive')
impotence = SideEffect.create(description: 'Impotence')
difficulty_having_an_orgasm = SideEffect.create(description: 'Difficulty Having An Orgasm')
tiredness = SideEffect.create(description: 'Tiredness')
vomiting = SideEffect.create(description: 'Vomiting')
increased_sweating = SideEffect.create(description: 'Increased Sweating')
diarrhea = SideEffect.create(description: 'Diarrhea')
gas = SideEffect.create(description: 'Gas')
sore_throat = SideEffect.create(description: 'Sore Throat')
anxiety = SideEffect.create(description: 'Anxiety')
insomnia = SideEffect.create(description: 'Insomnia')
unusual_dreams = SideEffect.create(description: 'Unusual Dreams')
skin_rash = SideEffect.create(description: 'Skin Rash')
heavy_menstrual_periods = SideEffect.create(description: 'Heavy Menstrual Periods')
muscle_pain = SideEffect.create(description: 'Muscle Pain')
abnormal_ejaculation = SideEffect.create(description: 'Abnormal Ejaculation')
yawning = SideEffect.create(description: 'Yawning')

elavil = Drug.create(brand_name: 'Elavil', generic_name: 'Amitriptyline', drug_type: 'Tricyclic')
DrugEffect.create(drug_id: elavil.id, side_effect_id: drowsiness.id)
DrugEffect.create(drug_id: elavil.id, side_effect_id: dry_mouth.id)
DrugEffect.create(drug_id: elavil.id, side_effect_id: dizziness.id)
DrugEffect.create(drug_id: elavil.id, side_effect_id: blurred_vision.id)
DrugEffect.create(drug_id: elavil.id, side_effect_id: constipation.id)
DrugEffect.create(drug_id: elavil.id, side_effect_id: weight_gain.id)
DrugEffect.create(drug_id: elavil.id, side_effect_id: trouble_urinating.id)
DrugEffect.create(drug_id: elavil.id, side_effect_id: headache.id)
DrugEffect.create(drug_id: elavil.id, side_effect_id: increased_appetite.id)
DrugEffect.create(drug_id: elavil.id, side_effect_id: changes_in_taste.id)

aventyl = Drug.create(brand_name: 'Aventyl, Pamelor', generic_name: 'Nortriptyline', drug_type: 'Tricyclic')
DrugEffect.create(drug_id: aventyl.id, side_effect_id: fast_heart_rate.id)
DrugEffect.create(drug_id: aventyl.id, side_effect_id: blurred_vision.id)
DrugEffect.create(drug_id: aventyl.id, side_effect_id: trouble_urinating.id)
DrugEffect.create(drug_id: aventyl.id, side_effect_id: dry_mouth.id)
DrugEffect.create(drug_id: aventyl.id, side_effect_id: constipation.id)
DrugEffect.create(drug_id: aventyl.id, side_effect_id: weight_gain.id)
DrugEffect.create(drug_id: aventyl.id, side_effect_id: weight_loss.id)
DrugEffect.create(drug_id: aventyl.id, side_effect_id: dizziness.id)
DrugEffect.create(drug_id: aventyl.id, side_effect_id: tingly_feeling.id)
DrugEffect.create(drug_id: aventyl.id, side_effect_id: weakness.id)
DrugEffect.create(drug_id: aventyl.id, side_effect_id: lack_of_coordination.id)
DrugEffect.create(drug_id: aventyl.id, side_effect_id: unpleasant_taste.id)
DrugEffect.create(drug_id: aventyl.id, side_effect_id: nausea.id)
DrugEffect.create(drug_id: aventyl.id, side_effect_id: ringing.id)
DrugEffect.create(drug_id: aventyl.id, side_effect_id: breast_swelling.id)
DrugEffect.create(drug_id: aventyl.id, side_effect_id: decreased_sex_drive.id)
DrugEffect.create(drug_id: aventyl.id, side_effect_id: impotence.id)
DrugEffect.create(drug_id: aventyl.id, side_effect_id: difficulty_having_an_orgasm.id)

doxepin = Drug.create(brand_name: 'Prudoxin, Silenor, Zonalon, Sinequan', generic_name: 'Doxepin', drug_type: 'Tricyclic')
DrugEffect.create(drug_id: doxepin.id, side_effect_id: drowsiness.id)
DrugEffect.create(drug_id: doxepin.id, side_effect_id: dizziness.id)
DrugEffect.create(drug_id: doxepin.id, side_effect_id: tiredness.id)
DrugEffect.create(drug_id: doxepin.id, side_effect_id: dry_mouth.id)
DrugEffect.create(drug_id: doxepin.id, side_effect_id: blurred_vision.id)
DrugEffect.create(drug_id: doxepin.id, side_effect_id: ringing.id)
DrugEffect.create(drug_id: doxepin.id, side_effect_id: nausea.id)
DrugEffect.create(drug_id: doxepin.id, side_effect_id: vomiting.id)
DrugEffect.create(drug_id: doxepin.id, side_effect_id: constipation.id)
DrugEffect.create(drug_id: doxepin.id, side_effect_id: weight_gain.id)
DrugEffect.create(drug_id: doxepin.id, side_effect_id: increased_sweating.id)
DrugEffect.create(drug_id: doxepin.id, side_effect_id: breast_swelling.id)
DrugEffect.create(drug_id: doxepin.id, side_effect_id: decreased_sex_drive.id)
DrugEffect.create(drug_id: doxepin.id, side_effect_id: trouble_urinating.id)

fluvoxamine = Drug.create(brand_name: 'Luvox', generic_name: 'Fluvoxamine', drug_type: 'SSRI')
DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: decreased_appetite.id)
DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: nausea.id)
DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: diarrhea.id)
DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: gas.id)
DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: dry_mouth.id)
DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: sore_throat.id)
DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: dizziness.id)
DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: drowsiness.id)
DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: weakness.id)
DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: yawning.id)
DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: anxiety.id)
DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: insomnia.id)
DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: unusual_dreams.id)
DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: increased_sweating.id)
DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: skin_rash.id)
DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: heavy_menstrual_periods.id)
DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: muscle_pain.id)
DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: decreased_sex_drive.id)
DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: abnormal_ejaculation.id)
DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: difficulty_having_an_orgasm.id)

# imipramine = Drug.create(brand_name: 'Tofranil', generic_name: 'Imipramine', drug_type: 'Tricyclic')
# DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: decreased_appetite.id)
# DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: nausea.id)
# DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: diarrhea.id)
# DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: gas.id)
# DrugEffect.create(drug_id: doxepin.id, side_effect_id: dry_mouth.id)
# DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: sore_throat.id)
# DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: dizziness.id)
# DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: drowsiness.id)
# DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: weakness.id)
# DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: yawning.id)
# DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: anxiety.id)
# DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: insomnia.id)
# DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: unusual_dreams.id)
# DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: increased_sweating.id)
# DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: skin_rash.id)
# DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: heavy_menstrual_periods.id)
# DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: muscle_pain.id)
# DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: decreased_sex_drive.id)
# DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: abnormal_ejaculation.id)
# DrugEffect.create(drug_id: fluvoxamine.id, side_effect_id: difficulty_having_an_orgasm.id)
